import { ImageResponse } from "next/og";

/**
 * Modern favicon — a dynamically-rendered PNG of just the LogoMark
 * (no wordmark; illegible at 32px). Next.js auto-links this as
 * `<link rel="icon" type="image/png">` alongside the static
 * `app/favicon.ico` (legacy fallback, regenerated by
 * scripts/generate-favicon.mjs to match this same mark).
 *
 * Same Satori constraint as opengraph-image.tsx: no Tailwind
 * classes, no CSS custom properties — hardcoded hex from
 * app/globals.css, and LogoMark's SVG paths copied by hand with
 * `fill="#hex"` instead of `className="fill-*"`.
 */

export const size = { width: 32, height: 32 };
export const contentType = "image/png";

const TEAL_600 = "#2E8B84";
const RASPBERRY_600 = "#B83050";
const AMBER_500 = "#F5A623";
const CREAM = "#FEFDF5";

export default function Icon() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <svg width={32} height={32} viewBox="0 0 48 48" fill="none">
          <path
            d="M10 5h28a8 8 0 0 1 8 8v16a8 8 0 0 1-8 8H22l-9.5 7.6A1.5 1.5 0 0 1 10 47.4V37H10a8 8 0 0 1-8-8V13a8 8 0 0 1 8-8Z"
            fill={TEAL_600}
          />
          <path
            d="M14.5 22c2.6 4.2 6.4 6.4 9.5 6.4s6.9-2.2 9.5-6.4"
            stroke={CREAM}
            strokeWidth={3.4}
            strokeLinecap="round"
            fill="none"
          />
          <circle cx={38} cy={11} r={5} fill={RASPBERRY_600} />
          <circle cx={38} cy={11} r={1.9} fill={AMBER_500} />
        </svg>
      </div>
    ),
    { ...size },
  );
}
